name: ExtDN Actions
on: [pull_request]

jobs:
  integration-tests:
    strategy:
      matrix:
        magento_version: [2.3.7-p3, 2.4.5]
    name: Magento 2 Integration Tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_SQL_TO_RUN: 'GRANT ALL ON *.* TO "root"@"%";'
        ports:
          - 3306:3306
        options: --tmpfs /tmp:rw --tmpfs /var/lib/mysql:rw --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      es:
        image: docker.io/wardenenv/elasticsearch:7.8
        ports:
          - 9200:9200
        env:
          'discovery.type': single-node
          'xpack.security.enabled': false
          ES_JAVA_OPTS: "-Xms64m -Xmx512m"
        options: --health-cmd="curl localhost:9200/_cluster/health?wait_for_status=yellow&timeout=60s" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - if: matrix.magento_version == '2.3.7-p3'
        name: M2 Integration Tests on ${{ matrix.magento_version }}
        uses: MultiSafepay/github-actions-m2/magento-integration-tests/7.3@with-coverage-support
        env:
            MAGENTO_MARKETPLACE_USERNAME: ${{ secrets.MAGENTO_MARKETPLACE_USERNAME }}
            MAGENTO_MARKETPLACE_PASSWORD: ${{ secrets.MAGENTO_MARKETPLACE_PASSWORD }}
            GLOBAL_GITHUB_TOKEN: ${{ secrets.GLOBAL_GITHUB_TOKEN }}
            CURRENT_HEAD_REF: ${{ github.event.pull_request.head.ref }}
        with:
            module_name: MultiSafepay_ConnectMSI
            composer_name: multisafepay/magento2-msi
            ce_version: '${{ matrix.magento_version }}'
            magento_pre_install_script: .github/workflows/magento-integration-tests-pre-phpunit.sh
      - if: matrix.magento_version == '2.4.5'
        name: M2 Integration Tests on ${{ matrix.magento_version }}
        uses: MultiSafepay/github-actions-m2/magento-integration-tests/7.4@with-coverage-support
        env:
            MAGENTO_MARKETPLACE_USERNAME: ${{ secrets.MAGENTO_MARKETPLACE_USERNAME }}
            MAGENTO_MARKETPLACE_PASSWORD: ${{ secrets.MAGENTO_MARKETPLACE_PASSWORD }}
            GLOBAL_GITHUB_TOKEN: ${{ secrets.GLOBAL_GITHUB_TOKEN }}
            CURRENT_HEAD_REF: ${{ github.event.pull_request.head.ref }}
        with:
            module_name: MultiSafepay_ConnectMSI
            composer_name: multisafepay/magento2-msi
            ce_version: '${{ matrix.magento_version }}'
            magento_pre_install_script: .github/workflows/magento-integration-tests-pre-phpunit.sh
